// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPu_Ui489IrpHp_1UImq4-NHI8Yr1KSWs',
    appId: '1:29759211601:web:27955ab1975508186d9070',
    messagingSenderId: '29759211601',
    projectId: 'aniversariantes-51aa9',
    authDomain: 'aniversariantes-51aa9.firebaseapp.com',
    storageBucket: 'aniversariantes-51aa9.appspot.com',
    measurementId: 'G-LJF2F0HNZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKwog0VmjHFaxBCWd4LYDeLsqLFdrmM_I',
    appId: '1:29759211601:android:83e4ddb43f4b5b2a6d9070',
    messagingSenderId: '29759211601',
    projectId: 'aniversariantes-51aa9',
    storageBucket: 'aniversariantes-51aa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu-yEafGrFPJE1NyvsNW9TYNrUqW6kvag',
    appId: '1:29759211601:ios:364ebc7d45f799366d9070',
    messagingSenderId: '29759211601',
    projectId: 'aniversariantes-51aa9',
    storageBucket: 'aniversariantes-51aa9.appspot.com',
    iosClientId: '29759211601-lru4le67o64bq88re5il30a8s0m6fa68.apps.googleusercontent.com',
    iosBundleId: 'com.example.ageCalculator',
  );
}
