// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6DWerZQojXKG9Yz81KhN3EnKRsBqxeWY',
    appId: '1:342349213342:web:c246b7aab6e336e25e158f',
    messagingSenderId: '342349213342',
    projectId: 'captacao-de-clientes',
    authDomain: 'captacao-de-clientes.firebaseapp.com',
    storageBucket: 'captacao-de-clientes.appspot.com',
    measurementId: 'G-02QB0Q8L4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvplgQu04uN6T-O-yO3PG-RqVIN9VgmSI',
    appId: '1:342349213342:android:d426f8aa5cac493f5e158f',
    messagingSenderId: '342349213342',
    projectId: 'captacao-de-clientes',
    storageBucket: 'captacao-de-clientes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6HqOf6ehNhOHnmcDyIVO1aMqHJ3CR34w',
    appId: '1:342349213342:ios:ebcd50782fa4958c5e158f',
    messagingSenderId: '342349213342',
    projectId: 'captacao-de-clientes',
    storageBucket: 'captacao-de-clientes.appspot.com',
    iosClientId: '342349213342-b39hoseov65nbtq4u41244j42p4jko82.apps.googleusercontent.com',
    iosBundleId: 'com.example.ageCalculator',
  );
}
